spring:
  profiles:
    active: local
  config:
    import: application-naver-client.yaml
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:lsdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create # TODO 추후 옵션 변경
