# 기존의 NaverClient 관련 설정들
spring:
  config:
    activate:
      on-profile: local
external:
  naver:
    url: https://openapi.naver.com
    headers:
      client-id: ${NAVER_API_CLIENT_ID}
      client-secret: ${NAVER_API_CLIENT_SECRET}


